/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthCustomersIndexRouteImport } from './routes/_auth/customers/index'
import { Route as AuthCountriesIndexRouteImport } from './routes/_auth/countries/index'
import { Route as AuthCompaniesIndexRouteImport } from './routes/_auth/companies/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/_dashboard/index'
import { Route as AuthReportsCreateRouteImport } from './routes/_auth/reports/create'
import { Route as AuthCountriesCreateRouteImport } from './routes/_auth/countries/create'
import { Route as AuthCompaniesCreateRouteImport } from './routes/_auth/companies/create'
import { Route as AuthReportsEditReportIdRouteImport } from './routes/_auth/reports/edit.$reportId'
import { Route as AuthCustomersEditCustomerIdRouteImport } from './routes/_auth/customers/edit.$customerId'
import { Route as AuthCustomersDetailsCustomerIdRouteImport } from './routes/_auth/customers/details.$customerId'
import { Route as AuthCountriesEditCountryIdRouteImport } from './routes/_auth/countries/edit.$countryId'
import { Route as AuthCompaniesEditCompanyIdRouteImport } from './routes/_auth/companies/edit.$companyId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCustomersIndexRoute = AuthCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCountriesIndexRoute = AuthCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCompaniesIndexRoute = AuthCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReportsCreateRoute = AuthReportsCreateRouteImport.update({
  id: '/reports/create',
  path: '/reports/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCountriesCreateRoute = AuthCountriesCreateRouteImport.update({
  id: '/countries/create',
  path: '/countries/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCompaniesCreateRoute = AuthCompaniesCreateRouteImport.update({
  id: '/companies/create',
  path: '/companies/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReportsEditReportIdRoute = AuthReportsEditReportIdRouteImport.update({
  id: '/reports/edit/$reportId',
  path: '/reports/edit/$reportId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCustomersEditCustomerIdRoute =
  AuthCustomersEditCustomerIdRouteImport.update({
    id: '/customers/edit/$customerId',
    path: '/customers/edit/$customerId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthCustomersDetailsCustomerIdRoute =
  AuthCustomersDetailsCustomerIdRouteImport.update({
    id: '/customers/details/$customerId',
    path: '/customers/details/$customerId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthCountriesEditCountryIdRoute =
  AuthCountriesEditCountryIdRouteImport.update({
    id: '/countries/edit/$countryId',
    path: '/countries/edit/$countryId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthCompaniesEditCompanyIdRoute =
  AuthCompaniesEditCompanyIdRouteImport.update({
    id: '/companies/edit/$companyId',
    path: '/companies/edit/$companyId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginIndexRoute
  '/companies/create': typeof AuthCompaniesCreateRoute
  '/countries/create': typeof AuthCountriesCreateRoute
  '/reports/create': typeof AuthReportsCreateRoute
  '/': typeof AuthDashboardIndexRoute
  '/companies': typeof AuthCompaniesIndexRoute
  '/countries': typeof AuthCountriesIndexRoute
  '/customers': typeof AuthCustomersIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/companies/edit/$companyId': typeof AuthCompaniesEditCompanyIdRoute
  '/countries/edit/$countryId': typeof AuthCountriesEditCountryIdRoute
  '/customers/details/$customerId': typeof AuthCustomersDetailsCustomerIdRoute
  '/customers/edit/$customerId': typeof AuthCustomersEditCustomerIdRoute
  '/reports/edit/$reportId': typeof AuthReportsEditReportIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginIndexRoute
  '/companies/create': typeof AuthCompaniesCreateRoute
  '/countries/create': typeof AuthCountriesCreateRoute
  '/reports/create': typeof AuthReportsCreateRoute
  '/': typeof AuthDashboardIndexRoute
  '/companies': typeof AuthCompaniesIndexRoute
  '/countries': typeof AuthCountriesIndexRoute
  '/customers': typeof AuthCustomersIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/companies/edit/$companyId': typeof AuthCompaniesEditCompanyIdRoute
  '/countries/edit/$countryId': typeof AuthCountriesEditCountryIdRoute
  '/customers/details/$customerId': typeof AuthCustomersDetailsCustomerIdRoute
  '/customers/edit/$customerId': typeof AuthCustomersEditCustomerIdRoute
  '/reports/edit/$reportId': typeof AuthReportsEditReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_auth/companies/create': typeof AuthCompaniesCreateRoute
  '/_auth/countries/create': typeof AuthCountriesCreateRoute
  '/_auth/reports/create': typeof AuthReportsCreateRoute
  '/_auth/_dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/companies/': typeof AuthCompaniesIndexRoute
  '/_auth/countries/': typeof AuthCountriesIndexRoute
  '/_auth/customers/': typeof AuthCustomersIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
  '/_auth/companies/edit/$companyId': typeof AuthCompaniesEditCompanyIdRoute
  '/_auth/countries/edit/$countryId': typeof AuthCountriesEditCountryIdRoute
  '/_auth/customers/details/$customerId': typeof AuthCustomersDetailsCustomerIdRoute
  '/_auth/customers/edit/$customerId': typeof AuthCustomersEditCustomerIdRoute
  '/_auth/reports/edit/$reportId': typeof AuthReportsEditReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/companies/create'
    | '/countries/create'
    | '/reports/create'
    | '/'
    | '/companies'
    | '/countries'
    | '/customers'
    | '/reports'
    | '/companies/edit/$companyId'
    | '/countries/edit/$countryId'
    | '/customers/details/$customerId'
    | '/customers/edit/$customerId'
    | '/reports/edit/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/companies/create'
    | '/countries/create'
    | '/reports/create'
    | '/'
    | '/companies'
    | '/countries'
    | '/customers'
    | '/reports'
    | '/companies/edit/$companyId'
    | '/countries/edit/$countryId'
    | '/customers/details/$customerId'
    | '/customers/edit/$customerId'
    | '/reports/edit/$reportId'
  id:
    | '__root__'
    | '/_auth'
    | '/login/'
    | '/_auth/companies/create'
    | '/_auth/countries/create'
    | '/_auth/reports/create'
    | '/_auth/_dashboard/'
    | '/_auth/companies/'
    | '/_auth/countries/'
    | '/_auth/customers/'
    | '/_auth/reports/'
    | '/_auth/companies/edit/$companyId'
    | '/_auth/countries/edit/$countryId'
    | '/_auth/customers/details/$customerId'
    | '/_auth/customers/edit/$customerId'
    | '/_auth/reports/edit/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/customers/': {
      id: '/_auth/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/countries/': {
      id: '/_auth/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthCountriesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/companies/': {
      id: '/_auth/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthCompaniesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_dashboard/': {
      id: '/_auth/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reports/create': {
      id: '/_auth/reports/create'
      path: '/reports/create'
      fullPath: '/reports/create'
      preLoaderRoute: typeof AuthReportsCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/countries/create': {
      id: '/_auth/countries/create'
      path: '/countries/create'
      fullPath: '/countries/create'
      preLoaderRoute: typeof AuthCountriesCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/companies/create': {
      id: '/_auth/companies/create'
      path: '/companies/create'
      fullPath: '/companies/create'
      preLoaderRoute: typeof AuthCompaniesCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reports/edit/$reportId': {
      id: '/_auth/reports/edit/$reportId'
      path: '/reports/edit/$reportId'
      fullPath: '/reports/edit/$reportId'
      preLoaderRoute: typeof AuthReportsEditReportIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/customers/edit/$customerId': {
      id: '/_auth/customers/edit/$customerId'
      path: '/customers/edit/$customerId'
      fullPath: '/customers/edit/$customerId'
      preLoaderRoute: typeof AuthCustomersEditCustomerIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/customers/details/$customerId': {
      id: '/_auth/customers/details/$customerId'
      path: '/customers/details/$customerId'
      fullPath: '/customers/details/$customerId'
      preLoaderRoute: typeof AuthCustomersDetailsCustomerIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/countries/edit/$countryId': {
      id: '/_auth/countries/edit/$countryId'
      path: '/countries/edit/$countryId'
      fullPath: '/countries/edit/$countryId'
      preLoaderRoute: typeof AuthCountriesEditCountryIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/companies/edit/$companyId': {
      id: '/_auth/companies/edit/$companyId'
      path: '/companies/edit/$companyId'
      fullPath: '/companies/edit/$companyId'
      preLoaderRoute: typeof AuthCompaniesEditCompanyIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCompaniesCreateRoute: typeof AuthCompaniesCreateRoute
  AuthCountriesCreateRoute: typeof AuthCountriesCreateRoute
  AuthReportsCreateRoute: typeof AuthReportsCreateRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthCompaniesIndexRoute: typeof AuthCompaniesIndexRoute
  AuthCountriesIndexRoute: typeof AuthCountriesIndexRoute
  AuthCustomersIndexRoute: typeof AuthCustomersIndexRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
  AuthCompaniesEditCompanyIdRoute: typeof AuthCompaniesEditCompanyIdRoute
  AuthCountriesEditCountryIdRoute: typeof AuthCountriesEditCountryIdRoute
  AuthCustomersDetailsCustomerIdRoute: typeof AuthCustomersDetailsCustomerIdRoute
  AuthCustomersEditCustomerIdRoute: typeof AuthCustomersEditCustomerIdRoute
  AuthReportsEditReportIdRoute: typeof AuthReportsEditReportIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCompaniesCreateRoute: AuthCompaniesCreateRoute,
  AuthCountriesCreateRoute: AuthCountriesCreateRoute,
  AuthReportsCreateRoute: AuthReportsCreateRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthCompaniesIndexRoute: AuthCompaniesIndexRoute,
  AuthCountriesIndexRoute: AuthCountriesIndexRoute,
  AuthCustomersIndexRoute: AuthCustomersIndexRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
  AuthCompaniesEditCompanyIdRoute: AuthCompaniesEditCompanyIdRoute,
  AuthCountriesEditCountryIdRoute: AuthCountriesEditCountryIdRoute,
  AuthCustomersDetailsCustomerIdRoute: AuthCustomersDetailsCustomerIdRoute,
  AuthCustomersEditCustomerIdRoute: AuthCustomersEditCustomerIdRoute,
  AuthReportsEditReportIdRoute: AuthReportsEditReportIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
